// ── MASTER ROLE LIST ──────────────────────────────────────────
export const MASTER_ROLES = [
  { id: 'ceo', name: 'CEO', type: 'existing', level: 'L1' },
  { id: 'cfo', name: 'CFO / GM Corporate Services', type: 'existing', level: 'L1' },
  { id: 'gm_ps', name: 'GM Policy & Services', type: 'existing', level: 'L1' },
  { id: 'gm_se', name: 'GM Stakeholder Engagement', type: 'existing', level: 'L1' },
  { id: 'state_sec', name: 'State Secretary', type: 'existing', level: 'L1' },
  { id: 'gc', name: 'General Counsel', type: 'existing', level: 'L1/L2' },
  { id: 'asst_cosec', name: 'Assistant Company Secretary', type: 'existing', level: 'L3' },
  { id: 'ea_ceo', name: 'Executive Admin Assistant', type: 'existing', level: 'L5' },
  { id: 'tpp', name: 'Transformation Program Partner', type: 'existing', level: 'L4' },
  { id: 'mel_lead', name: 'Strategy & Impact Principal', type: 'existing', level: 'L3' },
  { id: 'mgr_digital', name: 'Manager, Digital Systems', type: 'existing', level: 'L3' },
  { id: 'paralegal', name: 'Paralegal', type: 'existing', level: 'L4' },
  { id: 'fin_mgr', name: 'Finance Manager', type: 'existing', level: 'L3' },
  { id: 'accountant', name: 'Accountant', type: 'existing', level: 'L4' },
  { id: 'asst_acct', name: 'Assistant Accountant', type: 'existing', level: 'L5' },
  { id: 'gov_mgr', name: 'Manager, Governance & Compliance', type: 'existing', level: 'L3' },
  { id: 'asst_cosec2', name: 'Asst Company Secretary (CoSec)', type: 'existing', level: 'L3' },
  { id: 'emp_exp', name: 'Manager, Employee Experience', type: 'existing', level: 'L3' },
  { id: 'hd_events', name: 'Head of Events', type: 'existing', level: 'L2' },
  { id: 'ev_support', name: 'Event Support', type: 'existing', level: 'L5' },
  { id: 'ea_statesec', name: 'EA to State Secretary', type: 'existing', level: 'L5' },
  { id: 'sb_adv_mgr', name: 'Sub-Branch Advisory Manager', type: 'existing', level: 'L3' },
  { id: 'eng_partner1', name: 'Engagement Partner 1', type: 'vacant', level: 'L4' },
  { id: 'eng_partner2', name: 'Engagement Partner 2', type: 'vacant', level: 'L4' },
  { id: 'mem_sup_sup', name: 'Member Support Supervisor', type: 'existing', level: 'L3' },
  { id: 'mem_officer', name: 'Membership Officer', type: 'existing', level: 'L5' },
  { id: 'admin_sup', name: 'Admin Support Officer', type: 'existing', level: 'L5' },
  { id: 'hd_vso', name: 'Head of Veteran Service Operations', type: 'vacant', level: 'L2' },
  { id: 'comm_svc_mgr', name: 'Community Services Manager', type: 'existing', level: 'L3' },
  { id: 'asp_mgr', name: 'Advocacy Support Program Manager', type: 'existing', level: 'L3' },
  { id: 'asp_coord', name: 'ASP Coordinator', type: 'existing', level: 'L4' },
  { id: 'comp_adv', name: 'Compensation Advocate Coordinator', type: 'existing', level: 'L4' },
  { id: 'wb_adv', name: 'Wellbeing Advocate Coordinator', type: 'existing', level: 'L4' },
  { id: 'vol_mgr', name: 'Volunteer Manager', type: 'existing', level: 'L3' },
  { id: 'vol_coord', name: 'Volunteer Coordinator', type: 'existing', level: 'L4' },
  { id: 'sr_coord', name: 'S+R Program State Coordinator', type: 'existing', level: 'L4' },
  { id: 'sr_support', name: 'S+R Program & Engagement Support', type: 'existing', level: 'L5' },
  { id: 'vfw_lead', name: 'Veteran & Family Wellbeing Lead', type: 'vacant', level: 'L3' },
  { id: 'int_comms', name: 'Internal Communications Specialist', type: 'existing', level: 'L4' },
  { id: 'comms_mgr', name: 'Comms & Marketing Campaigns Mgr', type: 'existing', level: 'L3' },
  { id: 'media_spec', name: 'Media & Content Specialist', type: 'existing', level: 'L4' },
  { id: 'mktg_svc', name: 'Mktg & Comms Specialist (Svc Del)', type: 'existing', level: 'L4' },
  { id: 'brand_spec', name: 'Brand & Partnerships Specialist', type: 'existing', level: 'L4' },
  { id: 'mktg_coord', name: 'Marketing & Comms Coordinator', type: 'existing', level: 'L4' },
  { id: 'pship_role1', name: 'Partnership Role 1', type: 'vacant', level: 'L3' },
  { id: 'pship_role2', name: 'Partnership Role 2', type: 'vacant', level: 'L3' },
  { id: 'hd_gr', name: 'Head, Govt Rels & Corp Affairs', type: 'existing', level: 'L2' },
  { id: 'hd_mktg_pship', name: 'Head, Marketing & Partnerships', type: 'existing', level: 'L2' },
  { id: 'policy_off', name: 'Policy Officer', type: 'existing', level: 'L3' },
  { id: 'it_out', name: 'IT (Outsourced)', type: 'outsourced', level: 'OUT' },
  { id: 'pc_out', name: 'P&C (Outsourced)', type: 'outsourced', level: 'OUT' },
  { id: 'cosec_out', name: 'CoSec (Outsourced)', type: 'outsourced', level: 'OUT' },
  { id: 'fundraising_mgr', name: 'Fundraising Manager', type: 'new', level: 'L3' },
  { id: 'crp_coord', name: 'CRP Coordinator', type: 'new', level: 'L3' },
  { id: 'mel_analyst', name: 'MEL / Data Analyst', type: 'new', level: 'L4' },
  { id: 'service_nav', name: 'Service Navigation Lead', type: 'new', level: 'L3' },
  { id: 'cos_role', name: 'Chief of Staff', type: 'new', level: 'ELT' },
  { id: 'connect_gm', name: 'Connect Lead / GM', type: 'new', level: 'L1' },
  { id: 'adv_gm', name: 'Advocacy Lead / GM', type: 'new', level: 'L1' },
  { id: 'sr_pol_analyst', name: 'Senior Policy Analyst', type: 'new', level: 'L3' },
  { id: 'comm_int', name: 'Comms — Internal Lead (Joanne)', type: 'new', level: 'L3' },
  { id: 'comm_ext', name: 'Comms — External Lead (Tony)', type: 'new', level: 'L3' },
  { id: 'svc_design', name: 'Service Design Lead', type: 'new', level: 'L3' },
  { id: 'brand_dir', name: 'Brand Strategy Director', type: 'new', level: 'L2' },
  { id: 'hd_fundraising', name: 'Head, Fundraising & Revenue', type: 'new', level: 'L2' },
  { id: 'crm_analyst', name: 'CRM Data Analyst', type: 'new', level: 'L4' },
  { id: 'comm_pship', name: 'Commercial Partnerships Manager', type: 'new', level: 'L3' },
  { id: 'change_spec', name: 'Change Management Specialist', type: 'new', level: 'L3' },
  { id: 'commemoration_lead', name: 'Commemoration Lead', type: 'vacant', level: 'L3' },
  { id: 'schools_ed', name: 'Schools & Community Education', type: 'new', level: 'L3' },
];

// ── GAP DATA ──────────────────────────────────────────────────
export const GAPS = [
  { cap: 'Data, CRM & Member Analytics', rating: 'RED', desc: 'Only 2 E-coded roles across 46. Strategy assumes CRM capability across Membership, Marketing and Veteran Support.', addr: { 0: false, 1: false, 2: true, 3: true } },
  { cap: 'Fundraising & Philanthropy', rating: 'RED', desc: 'Not in current framework. Activity 4.2 cannot execute without dedicated function.', addr: { 0: false, 1: false, 2: true, 3: true } },
  { cap: 'Policy Research & Govt Relations', rating: 'RED', desc: 'Absent as distinct domain — absorbed into Stakeholder Engagement.', addr: { 0: false, 1: false, 2: false, 3: true } },
  { cap: 'Research & Evaluation (Portfolio)', rating: 'RED', desc: 'Strategy & Impact Principal is sole E-coded role. Strategy evidence demands require a function.', addr: { 0: false, 1: false, 2: true, 3: true } },
  { cap: 'Portfolio Program Management', rating: 'RED', desc: 'No role holds 33 activities across 11 work streams. PMO in Options C/D directly addresses this.', addr: { 0: false, 1: false, 2: true, 3: true } },
  { cap: 'Brand Strategy & Architecture', rating: 'RED', desc: 'Multi-entity brand architecture requires internal strategic ownership. Currently execution-focused only.', addr: { 0: false, 1: false, 2: false, 3: true } },
  { cap: 'Service Design (Human-centred)', rating: 'AMBER', desc: "HCD methodology not coded anywhere. 'No wrong door' navigation model requires this.", addr: { 0: false, 1: false, 2: false, 3: true } },
  { cap: 'Commercial Partnership Governance', rating: 'AMBER', desc: 'RSL Lifecare and pipeline require commercial/legal skills beyond general stakeholder engagement.', addr: { 0: false, 1: false, 2: false, 3: true } },
  { cap: 'Org & Capacity Building', rating: 'AMBER', desc: 'OD practitioners absent. Sub Branch enablement at scale unresourced.', addr: { 0: false, 1: false, 2: false, 3: false } },
  { cap: 'Communications & Media (Proactive)', rating: 'AMBER', desc: 'Proactive media relations and rapid-response may be thin at specialist level.', addr: { 0: false, 1: false, 2: false, 3: true } },
  { cap: 'Events & Large-Scale Production', rating: 'AMBER', desc: 'ANZAC Day at scale may require dedicated events production expertise.', addr: { 0: true, 1: true, 2: true, 3: true } },
  { cap: 'Veteran Sector Knowledge', rating: 'GREEN', desc: 'E-coding at 30%. Strongest match in current framework.', addr: { 0: true, 1: true, 2: true, 3: true } },
];

// ── BASE OPTIONS ──────────────────────────────────────────────
export const BASE_OPTIONS = [
  {
    id: 0, label: 'Option A: Rump ANZAC House',
    desc: 'Stripped-back core of ~15–20 roles. Admin, sub-Branch support, comms only. Lean ELT: CEO, CFO, State Secretary. GC not ELT. No PMO.',
    risk: 'HIGH', riskCol: '#dc2626', isRec: false,
    metrics: { active: '~18', newRoles: '0', cost: '↓↓↓' },
    trackA: ['Lean ELT: CEO, CFO, State Secretary', 'GC retained — not ELT', 'CoSec, IT, P&C outsourced', 'All Veteran Support delivery removed', 'Stakeholder Engagement removed (lean comms only)', 'TPP wound down', 'State Secretary PD resolved'],
    trackB: ['None — no new investment'],
    teams: [
      { id: 'ceo-a', label: 'CEO', theme: 'th-elt', roleIds: ['ceo', 'gc', 'asst_cosec', 'ea_ceo', 'cosec_out'] },
      { id: 'state-a', label: 'State Secretary', theme: 'th-state', roleIds: ['state_sec', 'hd_events', 'ev_support', 'ea_statesec', 'sb_adv_mgr', 'eng_partner1', 'eng_partner2', 'mem_sup_sup'] },
      { id: 'corp-a', label: 'CFO / Corporate', theme: 'th-elt', roleIds: ['cfo', 'fin_mgr', 'accountant', 'asst_acct', 'it_out', 'pc_out'] },
      { id: 'comms-a', label: 'Comms (Lean)', theme: '', roleIds: ['int_comms'] },
      { id: 'removed-a', label: 'NOT IN OPTION A', theme: 'th-enable', isWrap: true, roleIds: ['gm_ps', 'gm_se', 'hd_vso', 'comm_svc_mgr', 'asp_mgr', 'asp_coord', 'comp_adv', 'wb_adv', 'vol_mgr', 'vol_coord', 'sr_coord', 'sr_support', 'vfw_lead', 'comms_mgr', 'media_spec', 'mktg_svc', 'hd_gr', 'hd_mktg_pship', 'brand_spec', 'mktg_coord', 'pship_role1', 'pship_role2', 'tpp', 'mel_lead', 'mgr_digital', 'gov_mgr', 'emp_exp', 'policy_off', 'paralegal', 'asst_cosec2', 'mem_officer', 'admin_sup'] },
    ],
  },
  {
    id: 1, label: 'Option B: Streamlined Existing',
    desc: 'Four-pillar structure with reporting corrections. GC direct to CEO (ELT TBD), Governance & Risk under GC. CoSec, IT, P&C outsourced. GM SE above Heads of GR and Marketing. No PMO.',
    risk: 'MOD-HIGH', riskCol: '#d97706', isRec: false,
    metrics: { active: '~38', newRoles: '0', cost: 'Neutral' },
    trackA: ['State Secretary PD resolved', 'GC direct to CEO — ELT TBD', 'Paralegal reports to GC', 'Asst Company Secretary direct to CEO', 'CoSec, IT, P&C outsourced', 'GM SE sits above Head of GR and Head of Marketing', '7 Veteran Services PDs updated', 'TPP wound down', 'L3 title inconsistencies corrected'],
    trackB: ['None — structural corrections only. Capability gaps accepted as managed risk.'],
    teams: [
      { id: 'ceo-b', label: 'CEO', theme: 'th-elt', roleIds: ['ceo', 'asst_cosec', 'ea_ceo', 'cosec_out'] },
      { id: 'gc-b', label: 'GC + Governance', theme: 'th-elt', roleIds: ['gc', 'paralegal', 'gov_mgr', 'asst_cosec2'] },
      { id: 'state-b', label: 'State Secretary', theme: 'th-state', roleIds: ['state_sec', 'ea_statesec', 'hd_events', 'ev_support', 'sb_adv_mgr', 'eng_partner1', 'eng_partner2', 'mem_sup_sup', 'mem_officer', 'admin_sup'] },
      { id: 'corp-b', label: 'CFO / Corporate', theme: 'th-elt', roleIds: ['cfo', 'fin_mgr', 'accountant', 'asst_acct', 'emp_exp', 'it_out', 'pc_out'] },
      { id: 'vet-b', label: 'GM Veteran Support', theme: '', roleIds: ['gm_ps', 'hd_vso', 'comm_svc_mgr', 'asp_mgr', 'asp_coord', 'comp_adv', 'wb_adv', 'vol_mgr', 'vol_coord', 'sr_coord', 'sr_support', 'mel_lead'] },
      {
        id: 'se-b', label: 'GM Stakeholder Engagement', theme: '', roleIds: ['gm_se'],
        subGroups: [
          { id: 'gr-b', label: 'Head, Govt Rels & Corp Affairs', roleIds: ['hd_gr', 'int_comms', 'comms_mgr', 'media_spec', 'mktg_svc', 'vfw_lead', 'policy_off'] },
          { id: 'mktg-b', label: 'Head, Marketing & Partnerships', roleIds: ['hd_mktg_pship', 'brand_spec', 'mktg_coord', 'pship_role1', 'pship_role2'] },
        ],
      },
    ],
  },
  {
    id: 2, label: 'Option C: Scaled + PMO ★',
    desc: 'Four-pillar structure with Track B investment. GC direct to CEO (ELT TBD), Governance & Risk under GC. CoSec outsourced. Formal PMO direct to CEO — TPP, Strategy & Impact Principal, Digital Systems Mgr. GM SE above Heads of GR and Marketing.',
    risk: 'MODERATE', riskCol: '#d97706', isRec: true,
    metrics: { active: '~42', newRoles: '3–4', cost: 'Neutral' },
    trackA: ['All Track A from Option B', 'Formal PMO direct to CEO (no named head initially)', 'TPP, Strategy & Impact Principal, Digital Systems Mgr in PMO', 'GC direct to CEO — Governance & Risk under GC', 'ELT portfolio review — individual discussions'],
    trackB: ['Fundraising Manager (Corporate Services)', 'MEL / Data Analyst — expand to small function', 'CRP Coordinator — strengthen Community / Connect', 'Portfolio reporting absorbed into PMO'],
    teams: [
      { id: 'ceo-c', label: 'CEO', theme: 'th-elt', roleIds: ['ceo', 'asst_cosec', 'ea_ceo', 'cosec_out'] },
      { id: 'pmo-c', label: 'PMO (Direct to CEO)', theme: 'th-pmo', roleIds: ['tpp', 'mel_lead', 'mgr_digital', 'mel_analyst'] },
      { id: 'gc-c', label: 'GC + Governance', theme: 'th-elt', roleIds: ['gc', 'paralegal', 'gov_mgr', 'asst_cosec2'] },
      { id: 'state-c', label: 'State Secretary', theme: 'th-state', roleIds: ['state_sec', 'ea_statesec', 'hd_events', 'ev_support', 'sb_adv_mgr', 'eng_partner1', 'eng_partner2', 'mem_sup_sup', 'mem_officer', 'admin_sup'] },
      { id: 'corp-c', label: 'CFO / Corporate', theme: 'th-elt', roleIds: ['cfo', 'fin_mgr', 'fundraising_mgr', 'accountant', 'asst_acct', 'it_out', 'pc_out'] },
      { id: 'vet-c', label: 'GM Veteran Support', theme: '', roleIds: ['gm_ps', 'hd_vso', 'comm_svc_mgr', 'asp_mgr', 'asp_coord', 'comp_adv', 'wb_adv', 'vol_mgr', 'vol_coord', 'sr_coord', 'sr_support', 'vfw_lead', 'crp_coord', 'service_nav'] },
      {
        id: 'se-c', label: 'GM Stakeholder Engagement', theme: '', roleIds: ['gm_se', 'emp_exp'],
        subGroups: [
          { id: 'gr-c', label: 'Head, Govt Rels & Corp Affairs', roleIds: ['hd_gr', 'int_comms', 'comms_mgr', 'media_spec', 'mktg_svc', 'policy_off'] },
          { id: 'mktg-c', label: 'Head, Marketing & Partnerships', roleIds: ['hd_mktg_pship', 'brand_spec', 'mktg_coord', 'pship_role1', 'pship_role2'] },
        ],
      },
    ],
  },
  {
    id: 3, label: 'Option D: Full Build-Out',
    desc: 'Four named delivery pillars. Chief of Staff off CEO heading Office of CoS: PMO + Governance & Risk + CoSec (all in-house). Addresses all critical and amber capability gaps. Requires Track B funding.',
    risk: 'LOWER', riskCol: '#15803d', isRec: false,
    metrics: { active: '~55+', newRoles: '8–10', cost: '+$400–600K p.a.' },
    trackA: ['All Track A from Option C', 'Appoint Chief of Staff — heads Office of CoS', 'Office of CoS: PMO + Governance & Risk + CoSec in-house', 'Restructure into four named delivery pillars', 'Commemoration as distinct function', 'Advocacy as dedicated pillar', 'Connect = SB Enablement + Veteran Support'],
    trackB: ['All Track B from Option C, plus:', 'Head of Fundraising & Revenue (senior hire)', 'Senior Policy Analyst', 'Brand Strategy Director', 'CRM Data Analyst + Platform Manager', 'Service Design Lead', 'Commercial Partnerships Manager', 'Change Management Specialist', 'Internal Comms Lead (Joanne) + External Comms Lead (Tony)'],
    teams: [
      { id: 'ceo-d', label: 'CEO', theme: 'th-elt', roleIds: ['ceo', 'asst_cosec', 'ea_ceo'] },
      { id: 'cos-d', label: 'Office of Chief of Staff', theme: 'th-cos', isCOS: true, roleIds: ['cos_role', 'tpp', 'mel_lead', 'mgr_digital', 'gov_mgr', 'asst_cosec2'] },
      { id: 'connect-d', label: 'CONNECT', theme: 'th-connect', roleIds: ['connect_gm', 'sb_adv_mgr', 'eng_partner1', 'eng_partner2', 'mem_sup_sup', 'mem_officer', 'admin_sup', 'hd_vso', 'comm_svc_mgr', 'asp_mgr', 'asp_coord', 'comp_adv', 'wb_adv', 'vol_mgr', 'vol_coord', 'sr_coord', 'sr_support', 'crp_coord', 'service_nav', 'svc_design', 'vfw_lead'] },
      { id: 'comm-d', label: 'COMMEMORATION', theme: 'th-comm', roleIds: ['state_sec', 'ea_statesec', 'hd_events', 'ev_support', 'commemoration_lead', 'schools_ed'] },
      { id: 'adv-d', label: 'ADVOCACY', theme: 'th-adv', roleIds: ['adv_gm', 'hd_gr', 'sr_pol_analyst', 'policy_off', 'comm_int', 'comm_ext', 'comm_pship', 'int_comms', 'comms_mgr', 'media_spec', 'mktg_svc'] },
      { id: 'enable-d', label: 'ENABLERS', theme: 'th-enable', roleIds: ['cfo', 'fin_mgr', 'accountant', 'asst_acct', 'hd_fundraising', 'fundraising_mgr', 'crm_analyst', 'brand_dir', 'hd_mktg_pship', 'brand_spec', 'mktg_coord', 'pship_role1', 'pship_role2', 'it_out', 'pc_out', 'change_spec'] },
      { id: 'gc-d', label: 'GC + Legal', theme: 'th-elt', roleIds: ['gc', 'paralegal'] },
      { id: 'se-d', label: 'GM Stakeholder Eng.', theme: '', roleIds: ['gm_se'] },
    ],
  },
];
